export const {
  DATABASE_ID,
  PROJECT_COLLECTION_ID,
  BLOG_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_PROJECT: APPWRITE_PROJECT_ID,
  NEXT_PUBLIC_BUCKET_ID: BUCKET_ID,
  NEXT_PUBLIC_APPWRITE_ENDPOINT: APPWRITE_ENDPOINT,
} = process.env;
